[2022-04-24 01:52:38,252] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: local_2_gcs_2_bq_dag.download_crash_dataset_task manual__2022-04-24T01:52:31.743537+00:00 [queued]>
[2022-04-24 01:52:38,295] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: local_2_gcs_2_bq_dag.download_crash_dataset_task manual__2022-04-24T01:52:31.743537+00:00 [queued]>
[2022-04-24 01:52:38,298] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 01:52:38,302] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-04-24 01:52:38,305] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 01:52:38,366] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_crash_dataset_task> on 2022-04-24 01:52:31.743537+00:00
[2022-04-24 01:52:38,378] {standard_task_runner.py:52} INFO - Started process 5099 to run task
[2022-04-24 01:52:38,426] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'local_2_gcs_2_bq_dag', 'download_crash_dataset_task', 'manual__2022-04-24T01:52:31.743537+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/download_2_gcs_dag_V2.py', '--cfg-path', '/tmp/tmps_e7a_st', '--error-file', '/tmp/tmp_g32_6ag']
[2022-04-24 01:52:38,432] {standard_task_runner.py:77} INFO - Job 37: Subtask download_crash_dataset_task
[2022-04-24 01:52:38,687] {logging_mixin.py:109} INFO - Running <TaskInstance: local_2_gcs_2_bq_dag.download_crash_dataset_task manual__2022-04-24T01:52:31.743537+00:00 [running]> on host 65283f82c270
[2022-04-24 01:52:38,905] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=local_2_gcs_2_bq_dag
AIRFLOW_CTX_TASK_ID=download_crash_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-04-24T01:52:31.743537+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-24T01:52:31.743537+00:00
[2022-04-24 01:52:38,925] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-04-24 01:52:38,939] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sS https://data.cityofchicago.org/resource/85ca-t3if.csv > /opt/***/85ca-t3if.csv']
[2022-04-24 01:52:39,117] {subprocess.py:85} INFO - Output:
[2022-04-24 01:52:40,422] {subprocess.py:93} INFO - Command exited with return code 0
[2022-04-24 01:52:40,521] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=local_2_gcs_2_bq_dag, task_id=download_crash_dataset_task, execution_date=20220424T015231, start_date=20220424T015238, end_date=20220424T015240
[2022-04-24 01:52:40,753] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-24 01:52:40,990] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
