[2022-04-29 03:06:43,937] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dataproc_example_dag.create_dataproc_cluster manual__2022-04-29T02:03:59.172852+00:00 [queued]>
[2022-04-29 03:06:43,998] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dataproc_example_dag.create_dataproc_cluster manual__2022-04-29T02:03:59.172852+00:00 [queued]>
[2022-04-29 03:06:44,004] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-29 03:06:44,013] {taskinstance.py:1239} INFO - Starting attempt 2 of 3
[2022-04-29 03:06:44,015] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-29 03:06:44,083] {taskinstance.py:1259} INFO - Executing <Task(DataprocCreateClusterOperator): create_dataproc_cluster> on 2022-04-29 02:03:59.172852+00:00
[2022-04-29 03:06:44,105] {standard_task_runner.py:52} INFO - Started process 2547 to run task
[2022-04-29 03:06:44,136] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dataproc_example_dag', 'create_dataproc_cluster', 'manual__2022-04-29T02:03:59.172852+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dataproc_spark_dagv2.py', '--cfg-path', '/tmp/tmp27sgk_8a', '--error-file', '/tmp/tmpsc4flbml']
[2022-04-29 03:06:44,146] {standard_task_runner.py:77} INFO - Job 10: Subtask create_dataproc_cluster
[2022-04-29 03:06:44,496] {logging_mixin.py:109} INFO - Running <TaskInstance: dataproc_example_dag.create_dataproc_cluster manual__2022-04-29T02:03:59.172852+00:00 [running]> on host c3ee2a0c6e37
[2022-04-29 03:06:44,877] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dataproc_example_dag
AIRFLOW_CTX_TASK_ID=create_dataproc_cluster
AIRFLOW_CTX_EXECUTION_DATE=2022-04-29T02:03:59.172852+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-29T02:03:59.172852+00:00
[2022-04-29 03:06:44,888] {dataproc.py:662} INFO - Creating cluster: dtc-capstone-cluster
[2022-04-29 03:06:44,899] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-29 03:09:15,311] {dataproc.py:606} INFO - Cluster created.
[2022-04-29 03:09:15,426] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dataproc_example_dag, task_id=create_dataproc_cluster, execution_date=20220429T020359, start_date=20220429T030643, end_date=20220429T030915
[2022-04-29 03:09:15,524] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-29 03:09:15,636] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
